import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "E-commerce Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <header className="bg-gradient-to-b from-orange-600 to-orange-500 text-white">
          {/* Container */}
          <section className="container mx-auto">
            {/* Top */}
            <section className="flex justify-between py-1 text-xs">
              {/* Left */}
              <div className="flex space-x-2">
                <p>Follow us on:</p>
                <nav>
                  <a
                    className="font-bold"
                    target="_blank"
                    href="https://www.facebook.com/"
                  >
                    Facebook
                  </a>
                </nav>
              </div>

              {/* Right */}
              <nav className="divide-x-2 [&>*]:px-2">
                <a href="/sign-up">Sign Up</a>
                <a href="/login">Login</a>
              </nav>
            </section>

            {/* Bottom */}
            <section className="flex items-center py-2">
              {/* Logo */}
              <h1 className="text-4xl font-bold">E-commerce</h1>

              {/* Search bar */}
              <div className="flex-1 px-8">
                {/* Input */}
                <section className="text-black">
                  <div className="flex">
                    <input className="p-2 w-full" />
                    <div className="bg-white flex">
                      <button className="px-2 text-orange-600 font-bold">
                        Search
                      </button>
                    </div>
                  </div>
                </section>

                {/* Recommendations */}
                <section className="text-xs py-1">
                  <ul className="flex text-gray-200 space-x-2">
                    <li>
                      <a href="/products">Products</a>
                    </li>
                    <li>
                      <a href="/products">Products</a>
                    </li>
                    <li>
                      <a href="/products">Products</a>
                    </li>
                  </ul>
                </section>
              </div>

              {/* Cart */}
              <div className="w-1/12">
                <a href="/cart">Cart</a>
              </div>
            </section>
          </section>
        </header>
        <main className="flex-1">{children}</main>
        <footer></footer>
      </body>
    </html>
  );
}
